// lib/core/utils/platform_helper_web.dart
// Web-only: uses dart:html to fetch blob URL bytes for Firebase Storage upload
// ignore: avoid_web_libraries_in_flutter
import 'dart:html' as html;
import 'dart:typed_data';

Future<String> getNativeTempDir() async => '';

Future<List<int>> readFileBytes(String path) async => [];

/// Fetches bytes from a blob: URL generated by flutter_sound on web.
/// Returns Uint8List so we can upload to Firebase Storage via putData().
Future<Uint8List> fetchBlobBytes(String blobUrl) async {
  final request = await html.HttpRequest.request(
    blobUrl,
    responseType: 'arraybuffer',
  );
  final buffer = request.response as ByteBuffer;
  return buffer.asUint8List();
}