// lib/core/utils/platform_helper_web.dart
// Web-only: uses dart:html to fetch blob URL bytes for Firebase Storage upload
// ignore: avoid_web_libraries_in_flutter
import 'dart:html' as html;
import 'dart:typed_data';

Future<String> getNativeTempDir() async => '';

Future<List<int>> readFileBytes(String path) async => [];

/// Fetches bytes from a blob: URL generated by flutter_sound on web.
/// Returns Uint8List so we can upload to Firebase Storage via putData().
Future<Uint8List> fetchBlobBytes(String blobUrl) async {
  final request = await html.HttpRequest.request(
    blobUrl,
    responseType: 'arraybuffer',
  );
  final buffer = request.response as ByteBuffer;
  return buffer.asUint8List();
}

/// Reads the browser's user agent to guess which app store to send
/// guests to from a shared link. Returns 'android', 'ios', or null
/// if neither is detected (e.g. desktop browser).
String? detectMobileOsNative() {
  final ua = html.window.navigator.userAgent.toLowerCase();
  if (ua.contains('android')) return 'android';
  if (ua.contains('iphone') || ua.contains('ipad') || ua.contains('ipod')) {
    return 'ios';
  }
  return null;
}