class LocationConstants {
  LocationConstants._();

  static const List<String> primaryCities = [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Lucknow',
    'Kochi',
    'Goa',
    'Surat',
    'Chandigarh',
    'Indore',
    'Bhopal',
    'Nagpur',
    'Visakhapatnam',
    'Coimbatore',
    'Vadodara',
  ];

  static const List<String> editProfileCities = [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Lucknow',
    'Surat',
    'Kochi',
    'Chandigarh',
    'Indore',
    'Coimbatore',
    'Goa',
    'Vizag',
    'Nagpur',
    'Bhopal',
    'Thiruvananthapuram',
  ];

  static const List<String> otherCities = [
    'Agra',
    'Ajmer',
    'Aligarh',
    'Allahabad',
    'Amritsar',
    'Aurangabad',
    'Bareilly',
    'Belgaum',
    'Bhilai',
    'Bhubaneswar',
    'Bilaspur',
    'Bokaro',
    'Cuttack',
    'Dehradun',
    'Dhanbad',
    'Dharamshala',
    'Dibrugarh',
    'Durgapur',
    'Ernakulam',
    'Erode',
    'Faridabad',
    'Gangtok',
    'Ghaziabad',
    'Gorakhpur',
    'Guntur',
    'Gurugram',
    'Guwahati',
    'Gwalior',
    'Hisar',
    'Hubli',
    'Imphal',
    'Jabalpur',
    'Jalandhar',
    'Jammu',
    'Jamnagar',
    'Jamshedpur',
    'Jhansi',
    'Jodhpur',
    'Jorhat',
    'Kanpur',
    'Karnal',
    'Kolhapur',
    'Kollam',
    'Kota',
    'Kozhikode',
    'Kurnool',
    'Ludhiana',
    'Madurai',
    'Mangalore',
    'Meerut',
    'Moradabad',
    'Mysuru',
    'Nanded',
    'Nashik',
    'Navi Mumbai',
    'Noida',
    'Patiala',
    'Patna',
    'Puducherry',
    'Raipur',
    'Rajkot',
    'Ranchi',
    'Rourkela',
    'Salem',
    'Shimla',
    'Siliguri',
    'Srinagar',
    'Thane',
    'Thiruvananthapuram',
    'Thrissur',
    'Tirupati',
    'Udaipur',
    'Udupi',
    'Varanasi',
    'Vellore',
    'Vijayawada',
    'Warangal',
  ];

  static const Map<String, String> cityIcons = {
    'Mumbai': 'assets/city_icons/mumbai.png',
    'Delhi': 'assets/city_icons/delhi.png',
    'Bangalore': 'assets/city_icons/bangalore.png',
    'Hyderabad': 'assets/city_icons/hyderabad.png',
    'Chennai': 'assets/city_icons/chennai.png',
    'Kolkata': 'assets/city_icons/kolkata.png',
    'Pune': 'assets/city_icons/pune.png',
    'Ahmedabad': 'assets/city_icons/ahmedabad.png',
    'Jaipur': 'assets/city_icons/jaipur.png',
    'Lucknow': 'assets/city_icons/lucknow.png',
    'Kochi': 'assets/city_icons/kochi.png',
    'Goa': 'assets/city_icons/goa.png',
    'Surat': 'assets/city_icons/surat.png',
    'Chandigarh': 'assets/city_icons/chandigarh.png',
    'Indore': 'assets/city_icons/indore.png',
    'Bhopal': 'assets/city_icons/bhopal.png',
    'Nagpur': 'assets/city_icons/nagpur.png',
    'Visakhapatnam': 'assets/city_icons/visakhapatnam.png',
    'Coimbatore': 'assets/city_icons/coimbatore.png',
    'Vadodara': 'assets/city_icons/vadodara.png',
  };

  static const List<String> states = [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
  ];

  static const Map<String, List<String>> stateCities = {
    'Andhra Pradesh': [
      'Visakhapatnam',
      'Vijayawada',
      'Tirupati',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Rajahmundry',
      'Kakinada',
      'Anantapur',
      'Kadapa',
    ],
    'Arunachal Pradesh': [
      'Itanagar',
      'Naharlagun',
      'Pasighat',
      'Tawang',
      'Ziro',
      'Bomdila',
      'Tezu',
      'Roing',
      'Khonsa',
      'Along',
    ],
    'Assam': [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tezpur',
      'Tinsukia',
      'Sivasagar',
      'Bongaigaon',
      'Goalpara',
    ],
    'Bihar': [
      'Patna',
      'Gaya',
      'Muzaffarpur',
      'Bhagalpur',
      'Darbhanga',
      'Aurangabad',
      'Purnia',
      'Ara',
      'Begusarai',
      'Katihar',
      'Munger',
    ],
    'Chhattisgarh': [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Raigarh',
      'Jagdalpur',
      'Ambikapur',
      'Dhamtari',
      'Rajnandgaon',
      'Mahasamund',
    ],
    'Goa': [
      'Panaji',
      'Margao',
      'Vasco da Gama',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Curchorem',
      'Canacona',
      'Sanquelim',
      'Valpoi',
    ],
    'Gujarat': [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Anand',
      'Gandhinagar',
      'Morbi',
    ],
    'Haryana': [
      'Gurugram',
      'Faridabad',
      'Panipat',
      'Ambala',
      'Hisar',
      'Karnal',
      'Rohtak',
      'Sonipat',
      'Yamunanagar',
      'Panchkula',
    ],
    'Himachal Pradesh': [
      'Shimla',
      'Manali',
      'Dharamshala',
      'Solan',
      'Mandi',
      'Hamirpur',
      'Una',
      'Bilaspur',
      'Kullu',
      'Chamba',
    ],
    'Jharkhand': [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro',
      'Deoghar',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
      'Chaibasa',
      'Medininagar',
    ],
    'Karnataka': [
      'Bengaluru',
      'Mysuru',
      'Mangaluru',
      'Hubballi',
      'Belagavi',
      'Shivamogga',
      'Davanagere',
      'Ballari',
      'Udupi',
      'Kalaburagi',
    ],
    'Kerala': [
      'Kochi',
      'Thiruvananthapuram',
      'Kozhikode',
      'Thrissur',
      'Kollam',
      'Kannur',
      'Alappuzha',
      'Palakkad',
      'Kottayam',
      'Malappuram',
    ],
    'Madhya Pradesh': [
      'Bhopal',
      'Indore',
      'Gwalior',
      'Jabalpur',
      'Ujjain',
      'Sagar',
      'Satna',
      'Ratlam',
      'Rewa',
      'Dewas',
    ],
    'Maharashtra': [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Nashik',
      'Thane',
      'Aurangabad',
      'Kolhapur',
      'Solapur',
      'Amravati',
      'Navi Mumbai',
    ],
    'Manipur': [
      'Imphal',
      'Thoubal',
      'Bishnupur',
      'Ukhrul',
      'Churachandpur',
      'Kakching',
      'Senapati',
      'Tamenglong',
      'Jiribam',
      'Moirang',
    ],
    'Meghalaya': [
      'Shillong',
      'Tura',
      'Jowai',
      'Nongpoh',
      'Baghmara',
      'Williamnagar',
      'Resubelpara',
      'Mawkyrwat',
      'Nongstoin',
      'Khliehriat',
    ],
    'Mizoram': [
      'Aizawl',
      'Lunglei',
      'Champhai',
      'Kolasib',
      'Serchhip',
      'Saiha',
      'Mamit',
      'Lawngtlai',
      'Saitual',
      'Khawzawl',
    ],
    'Nagaland': [
      'Kohima',
      'Dimapur',
      'Mokokchung',
      'Tuensang',
      'Mon',
      'Wokha',
      'Zunheboto',
      'Phek',
      'Kiphire',
      'Longleng',
    ],
    'Odisha': [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Puri',
      'Sambalpur',
      'Balasore',
      'Berhampur',
      'Jharsuguda',
      'Baripada',
      'Jeypore',
    ],
    'Punjab': [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Mohali',
      'Pathankot',
      'Moga',
      'Hoshiarpur',
      'Kapurthala',
    ],
    'Rajasthan': [
      'Jaipur',
      'Jodhpur',
      'Udaipur',
      'Kota',
      'Ajmer',
      'Bikaner',
      'Alwar',
      'Bharatpur',
      'Sikar',
      'Pali',
    ],
    'Sikkim': [
      'Gangtok',
      'Namchi',
      'Gyalshing',
      'Mangan',
      'Rangpo',
      'Singtam',
      'Jorethang',
      'Ravangla',
      'Pakyong',
      'Soreng',
    ],
    'Tamil Nadu': [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Salem',
      'Tiruchirappalli',
      'Tirunelveli',
      'Erode',
      'Vellore',
      'Thoothukudi',
      'Kanchipuram',
    ],
    'Telangana': [
      'Hyderabad',
      'Warangal',
      'Karimnagar',
      'Nizamabad',
      'Khammam',
      'Ramagundam',
      'Mahbubnagar',
      'Siddipet',
      'Adilabad',
      'Nalgonda',
    ],
    'Tripura': [
      'Agartala',
      'Udaipur',
      'Dharmanagar',
      'Kailasahar',
      'Belonia',
      'Ambassa',
      'Khowai',
      'Sabroom',
      'Teliamura',
      'Sonamura',
    ],
    'Uttar Pradesh': [
      'Lucknow',
      'Kanpur',
      'Noida',
      'Ghaziabad',
      'Agra',
      'Varanasi',
      'Prayagraj',
      'Meerut',
      'Bareilly',
      'Gorakhpur',
    ],
    'Uttarakhand': [
      'Dehradun',
      'Haridwar',
      'Rishikesh',
      'Haldwani',
      'Roorkee',
      'Nainital',
      'Rudrapur',
      'Kashipur',
      'Almora',
      'Pithoragarh',
    ],
    'West Bengal': [
      'Kolkata',
      'Howrah',
      'Durgapur',
      'Siliguri',
      'Asansol',
      'Kharagpur',
      'Bardhaman',
      'Malda',
      'Haldia',
      'Darjeeling',
    ],
  };

  static const List<Map<String, dynamic>> radiusOptions = [
    {'label': '2 km', 'value': 2.0},
    {'label': '5 km', 'value': 5.0},
    {'label': '10 km', 'value': 10.0},
    {'label': '20 km', 'value': 20.0},
    {'label': '50 km', 'value': 50.0},
    {'label': 'Entire City', 'value': -1.0},
  ];
}
